name: Publish snap

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      snap: ${{ steps.build.outputs.snap }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Complete git history is required to generate the version from git tags.
      - uses: snapcore/action-build@v1
        id: build
      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.build.outputs.snap }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: latest/edge